// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNXrarlK_pBV_tpa54Lflzlt6zTQn2hag',
    appId: '1:629612698082:web:773125fb6c8daf9eb441bb',
    messagingSenderId: '629612698082',
    projectId: 'eco-buy-536',
    authDomain: 'eco-buy-536.firebaseapp.com',
    storageBucket: 'eco-buy-536.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVK3iKvmCDkY0aYDXWir3FBCuAbQyE0vI',
    appId: '1:629612698082:android:04a960b3bc7fb794b441bb',
    messagingSenderId: '629612698082',
    projectId: 'eco-buy-536',
    storageBucket: 'eco-buy-536.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNXrarlK_pBV_tpa54Lflzlt6zTQn2hag',
    appId: '1:629612698082:web:5a6947ff5b970b97b441bb',
    messagingSenderId: '629612698082',
    projectId: 'eco-buy-536',
    authDomain: 'eco-buy-536.firebaseapp.com',
    storageBucket: 'eco-buy-536.firebasestorage.app',
  );
}
